language: php
 
# list any PHP version you want to test against
php:
  - 5.3
  - 5.4
  - 5.5
  
matrix:
  allow_failures:
    - php: 5.5
     
# Handle git submodules manually
git:
  submodules: false

env: DBCREDS=root
  
before_script:
  # Use sed to replace the SSH URL with the public URL, then initialize
  # submodules before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  
  - composer self-update
  - pyrus channel-discover pear.drush.org
  - pyrus install drush/drush-5.10.0.0
  - phpenv rehash
  # stubbing sendmail path with true to prevent delivery errors
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install php packages required for running a web server from drush on php 5.3
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

# # Create new site
#   - mysql -e 'create database luggage;'
  
# #  - php -d sendmail_path=`which true`
#   - drush si testing -y --db-url=mysql://travis@localhost/luggage --site-name=luggage --account-name=root install_configure_form.update_status_module='array(FALSE,FALSE)'
#   - drush --yes en simpletest
  
# # Install Omega and Suitcase
#   - drush en -y suitcase
#   - drush vset theme_default suitcase

# # Install all the Luggage features.
#   - drush -v en -y luggage_announcements luggage_biblio luggage_ckeditor luggage_contrib luggage_core luggage_events luggage_events_solr luggage_indicator luggage_news luggage_people luggage_people_solr luggage_placeholder luggage_projects luggage_resources luggage_resources_solr luggage_roles luggage_roles_solr luggage_seo luggage_solr luggage_ui luggage_vars suitcase_config suitcase_frontpanel
#   - drush fra -y
#   - drush cc all --yes
#   - drush runserver --server=builtin 8080 &
#   - sleep 4
#   - drush vset --yes simpletest_verbose FALSE

script:
  - bash scripts/build_luggage.sh
  # - drush test-run 'luggage' --debug --uri=http://127.0.0.1:8080
  
after_script:
  - drush runserver --server=builtin 8080 &
  - sleep 4
  - drush vset --yes simpletest_verbose FALSE
  - drush test-run 'luggage' --debug --uri=http://127.0.0.1:8080
  
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org##luggage"
    on_success: never
    on_failure: always
 
